### ISSUE TITLE
suggestion: change title color

### ISSUE THREAD

**Issue by Suyog002** [Suyog76/SMP-Git#1]
I think that it looks better if the main title is blue.

The styling rule could be changed like this:

```css
h1 {
  color: #b2e8d2;
}
```
